---
name: integration-test
on: workflow_call
jobs:
  integration-test:
    runs-on: ubuntu-latest
    permissions: {}
    env:
      GITHUB_TOKEN: ${{github.token}}
      AQUA_LOG_LEVEL: debug
      AQUA_LOG_COLOR: always
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: 1.20.3
          cache: true

      - run: go install ./cmd/pinact
      - run: pinact -v
      - run: pinact run testdata/foo.yaml
